version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  server:
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

volumes: 
  db-data:
