CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE if not exists users ( 
	id UUID PRIMARY KEY NOT NULL DEFAULT (uuid_generate_v4()),
	username TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	password TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
