CREATE TABLE if not exists refresh_token ( 
	id UUID PRIMARY KEY NOT NULL DEFAULT (uuid_generate_v4()),
    session_id UUID NOT NULL REFERENCES session_table,
	expired_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
